# Generated by Django 5.2.7 on 2026-01-20 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_billingunit_status_payoutbatch_and_more'),
        ('freelancer', '0006_freelancerprofile_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingunit',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_units', to='freelancer.freelancerprofile'),
        ),
        migrations.AlterField(
            model_name='payoutbatch',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_batches', to='freelancer.freelancerprofile'),
        ),
    ]
