# Generated by Django 5.2.7 on 2026-01-21 13:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_billingunit_freelancer_and_more'),
        ('freelancer', '0007_remove_freelancerprofile_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('total_gross', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_net', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('void', 'Void')], default='issued', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='freelancer.freelancerprofile')),
                ('payout_batch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='billing.payoutbatch')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
