# Generated by Django 5.2.7 on 2026-02-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='reference_id',
            field=models.CharField(blank=True, help_text='External or internal reference (subscription, escrow, payout, etc.)', max_length=100, null=True),
        ),
    ]
