# Generated by Django 5.2.7 on 2025-12-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0010_alter_usersubscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_detected_timezone',
            field=models.CharField(blank=True, help_text='Last timezone detected from browser (UI only)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', help_text='User preferred timezone (used for emails & scheduling)', max_length=64),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['timezone'], name='users_timezon_59d03e_idx'),
        ),
    ]
