# Generated by Django 5.2.7 on 2026-01-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_last_detected_timezone_user_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
