# Generated by Django 5.2.7 on 2026-02-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_clientprofile_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='assignment_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='team_size',
        ),
    ]
