# Generated by Django 5.2.7 on 2026-05-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_project_options_remove_project_assignment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
