# Generated by Django 5.2.7 on 2026-05-17 07:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_usersubscription_stripe_session_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'ordering': ['purchased_at']},
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='start_date',
        ),
        migrations.AddField(
            model_name='project',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='users.usersubscription'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='purchased_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('active', 'Active'), ('expired', 'Expired'), ('consumed', 'Consumed')], default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
