# Generated by Django 5.2.7 on 2025-11-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_alter_freelancerprofile_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='freelancer_resumes/'),
        ),
    ]
