# Generated by Django 5.2.7 on 2025-11-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_freelancerprofile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='freelancer_profiles/'),
        ),
    ]
