# Generated by Django 5.2.7 on 2026-01-20 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0005_alter_skill_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='stripe_charges_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='stripe_last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='stripe_payouts_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='stripe_requirements',
            field=models.JSONField(blank=True, help_text='Stripe missing requirements snapshot', null=True),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified by platform admin'),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
