# Generated by Django 5.2.7 on 2026-01-21 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0006_freelancerprofile_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='stripe_account_id',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='stripe_charges_enabled',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='stripe_last_synced_at',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='stripe_payouts_enabled',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='stripe_requirements',
        ),
    ]
