# Generated by Django 5.2.7 on 2026-01-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0007_remove_freelancerprofile_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='fixed_price',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='min_price',
        ),
        migrations.AddField(
            model_name='pricing',
            name='max_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='min_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='pricing_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('range', 'Hourly Range')], max_length=10),
        ),
    ]
