# Generated by Django 5.2.7 on 2026-02-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0008_remove_pricing_fixed_price_remove_pricing_max_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
