# Generated by Django 5.2.7 on 2026-02-17 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0009_freelancerprofile_average_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.AddField(
            model_name='skill',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='skills', to='freelancer.category'),
        ),
        migrations.AlterField(
            model_name='freelancerskill',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='freelancer.freelancerprofile'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
