# Generated by Django 5.2.7 on 2026-01-07 05:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0011_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Platform fee at the time of contract creation', max_digits=5)),
                ('scope_summary', models.TextField(help_text='Short description of agreed scope / deliverables')),
                ('termination_notice_days', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('disputed', 'Disputed')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='applications.offer')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='contract_co_status_601477_idx'), models.Index(fields=['offer'], name='contract_co_offer_i_912c33_idx')],
            },
        ),
    ]
