# Generated by Django 5.2.7 on 2026-01-10 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_trackingpolicy'),
        ('contract', '0002_contractdocumentfolder_contractdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='tracking_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminpanel.trackingpolicy'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tracking_required',
            field=models.BooleanField(default=False),
        ),
    ]
