# Generated by Django 5.2.7 on 2026-02-14 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_terminationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer_rating', models.PositiveSmallIntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('freelancer_review', models.TextField(blank=True)),
                ('platform_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('platform_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.OneToOneField(help_text='Review exists only for ended contracts', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='contract.contract')),
            ],
            options={
                'indexes': [models.Index(fields=['freelancer_rating'], name='contract_co_freelan_ee988a_idx'), models.Index(fields=['created_at'], name='contract_co_created_582e61_idx')],
            },
        ),
    ]
