# Generated by Django 5.2.7 on 2026-02-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_contractreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('completed', 'Completed Normally'), ('terminated', 'Terminated Early')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('disputed', 'Disputed')], default='active', max_length=20),
        ),
    ]
