# Generated by Django 5.2.7 on 2025-12-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('interviewing', 'Interviewing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20),
        ),
    ]
