# Generated by Django 5.2.7 on 2025-12-14 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_proposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_system_managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposal',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('interviewing', 'Interviewing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('auto_rejected', 'Auto Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20),
        ),
        migrations.CreateModel(
            name='ProposalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_match', models.FloatField()),
                ('experience_match', models.FloatField()),
                ('budget_fit', models.FloatField()),
                ('reliability', models.FloatField()),
                ('final_score', models.FloatField(db_index=True)),
                ('red_flags', models.JSONField(blank=True, default=list)),
                ('auto_reject', models.BooleanField(default=False)),
                ('auto_reject_reason', models.TextField(blank=True)),
                ('scored_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='applications.proposal')),
            ],
        ),
    ]
