# Generated by Django 5.2.7 on 2025-12-14 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_proposal_is_system_managed_proposal_rejected_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalscore',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='applications.proposal'),
        ),
    ]
