# Generated by Django 5.2.7 on 2025-12-14 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_proposalscore_proposal'),
        ('users', '0010_alter_usersubscription_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_weight', models.FloatField(default=0.4)),
                ('experience_weight', models.FloatField(default=0.3)),
                ('budget_weight', models.FloatField(default=0.2)),
                ('reliability_weight', models.FloatField(default=0.1)),
                ('min_final_score', models.FloatField(default=50)),
                ('auto_reject_on_red_flags', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_config', to='users.project')),
            ],
        ),
    ]
