# Generated by Django 5.2.7 on 2025-12-14 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_projectscoringconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectscoringconfig',
            options={'verbose_name': 'Global Scoring Config', 'verbose_name_plural': 'Global Scoring Configs'},
        ),
        migrations.AlterModelOptions(
            name='proposalscore',
            options={'ordering': ['-scored_at']},
        ),
        migrations.RemoveField(
            model_name='projectscoringconfig',
            name='project',
        ),
        migrations.AddField(
            model_name='projectscoringconfig',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Entry'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default=django.utils.timezone.now, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposalscore',
            name='experience_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proposalscore',
            name='is_latest',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='proposalscore',
            name='scored_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='proposalscore',
            index=models.Index(fields=['proposal', 'is_latest'], name='application_proposa_5d7a08_idx'),
        ),
    ]
