# Generated by Django 5.2.7 on 2025-12-19 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_chatroom_message_and_more'),
        ('freelancer', '0005_alter_skill_category'),
        ('users', '0010_alter_usersubscription_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_projects', to='freelancer.freelancerprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_freelancers', to='users.project')),
            ],
            options={
                'db_table': 'saved_projects',
                'indexes': [models.Index(fields=['freelancer', 'project'], name='saved_proje_freelan_9d7e57_idx')],
                'constraints': [models.UniqueConstraint(fields=('freelancer', 'project'), name='unique_freelancer_saved_project')],
            },
        ),
    ]
