# Generated by Django 5.2.7 on 2025-12-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_savedproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedproject',
            old_name='created_at',
            new_name='saved_at',
        ),
    ]
