# Generated by Django 5.2.7 on 2025-12-24 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_rename_created_at_savedproject_saved_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('interview', 'Interview'), ('review', 'Review')], max_length=20)),
                ('zego_room_id', models.CharField(db_index=True, editable=False, max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('actual_started_at', models.DateTimeField(blank=True, null=True)),
                ('actual_ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_token_issued_at', models.DateTimeField(blank=True, help_text='Last time a Zego token was issued', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='applications.chatroom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='applications.proposal')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['status', 'start_time'], name='application_status_87f278_idx'), models.Index(fields=['proposal', 'meeting_type'], name='application_proposa_d5d36d_idx'), models.Index(fields=['zego_room_id'], name='application_zego_ro_92bc39_idx')],
            },
        ),
    ]
