# Generated by Django 5.2.7 on 2026-01-20 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_offer'),
        ('freelancer', '0006_freelancerprofile_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='freelancer.freelancerprofile'),
        ),
    ]
