# Generated by Django 5.2.7 on 2026-01-27 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_alter_offer_freelancer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('escrowed', 'Escrowed'), ('released', 'Released'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('escrowed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refundable_until', models.DateTimeField(blank=True, null=True)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='applications.offer')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='application_status_ec661f_idx')],
            },
        ),
    ]
