# Generated by Django 5.2.7 on 2026-01-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_escrowpayment'),
    ]

    operations = [
        # ❌ Remove old pricing fields
        migrations.RemoveField(
            model_name='offer',
            name='fixed_rate',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='rate_type',
        ),

        # ✅ Add new escrow-based pricing fields (nullable first)
        migrations.AddField(
            model_name='offer',
            name='total_budget',
            field=models.DecimalField(
                max_digits=12,
                decimal_places=2,
                null=True,
                help_text='Total escrow amount paid upfront by client',
            ),
        ),
        migrations.AddField(
            model_name='offer',
            name='agreed_hourly_rate',
            field=models.DecimalField(
                max_digits=10,
                decimal_places=2,
                null=True,
                help_text='Hourly rate agreed for payouts',
            ),
        ),
        migrations.AddField(
            model_name='offer',
            name='estimated_hours',
            field=models.PositiveIntegerField(
                null=True,
                blank=True,
                help_text='Optional estimation for clarity',
            ),
        ),

        # 🔧 Minor field normalizations
        migrations.AlterField(
            model_name='escrowpayment',
            name='amount',
            field=models.DecimalField(
                max_digits=12,
                decimal_places=2,
                help_text='Total escrow amount charged via Stripe',
            ),
        ),
        migrations.AlterField(
            model_name='escrowpayment',
            name='refundable_until',
            field=models.DateTimeField(
                null=True,
                blank=True,
                help_text='Optional dispute window',
            ),
        ),
        migrations.AlterField(
            model_name='offer',
            name='valid_until',
            field=models.DateTimeField(),
        ),
    ]
