# Generated by Django 5.2.7 on 2026-01-30 06:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_remove_offer_fixed_rate_remove_offer_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='agreed_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hourly rate agreed for payouts', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total escrow amount paid upfront by client', max_digits=12),
        ),
    ]
