# Generated by Django 5.2.7 on 2026-02-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_alter_offer_agreed_hourly_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escrowpayment',
            old_name='escrowed_at',
            new_name='funded_at',
        ),
        migrations.RenameField(
            model_name='escrowpayment',
            old_name='refunded_at',
            new_name='settled_at',
        ),
        migrations.RemoveField(
            model_name='escrowpayment',
            name='released_at',
        ),
        migrations.AddField(
            model_name='escrowpayment',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='escrowpayment',
            name='released_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='escrowpayment',
            name='refundable_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escrowpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('funded', 'Funded'), ('settled', 'Settled'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
