# Generated by Django 5.2.7 on 2026-05-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_alter_offer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('funded', 'Funded'), ('settled', 'Settled'), ('refund_processing', 'Refund Processing'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
