# Generated by Django 5.2.7 on 2026-05-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_escrowpayment_refunded_at_escrowpayment_refunded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowpayment',
            name='refundable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
