# Generated by Django 5.2.7 on 2025-11-30 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='max_ptojects',
            new_name='max_projects',
        ),
    ]
