# Generated by Django 5.2.7 on 2026-01-10 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0002_contractdocumentfolder_contractdocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_index', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('is_idle', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['block_index'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('device_name', models.CharField(max_length=255)),
                ('os_name', models.CharField(max_length=100)),
                ('os_version', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenshotWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_count', models.PositiveSmallIntegerField()),
                ('offsets', models.JSONField()),
                ('used_offsets', models.JSONField(default=list)),
                ('seed', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screenshot_window', to='tracking.timeblock')),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_screenshots/%Y/%m/%d/')),
                ('image_hash', models.CharField(db_index=True, max_length=64)),
                ('screen_index', models.PositiveIntegerField(default=0)),
                ('resolution', models.CharField(max_length=50)),
                ('taken_at_client', models.DateTimeField()),
                ('taken_at_server', models.DateTimeField()),
                ('is_blurred', models.BooleanField(default=False)),
                ('blur_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='tracking.timeblock')),
            ],
            options={
                'ordering': ['taken_at_server'],
            },
        ),
        migrations.CreateModel(
            name='WorkConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_version', models.CharField(max_length=20)),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.device')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_consents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='contract.contract')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='tracking.device')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='timeblock',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='tracking.worksession'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SESSION_START', 'Session Start'), ('SESSION_STOP', 'Session Stop'), ('BLOCK_CREATED', 'Block Created'), ('SCREENSHOT', 'Screenshot'), ('IDLE', 'Idle'), ('ERROR', 'Error')], max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.worksession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['freelancer'], name='tracking_de_freelan_fabfcb_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_id'], name='tracking_de_device__c8aaa5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('freelancer', 'device_id')},
        ),
        migrations.AlterUniqueTogether(
            name='screenshot',
            unique_together={('time_block', 'image_hash')},
        ),
        migrations.AddIndex(
            model_name='workconsent',
            index=models.Index(fields=['freelancer', 'contract'], name='tracking_wo_freelan_408783_idx'),
        ),
        migrations.AddIndex(
            model_name='workconsent',
            index=models.Index(fields=['device'], name='tracking_wo_device__234945_idx'),
        ),
        migrations.AddIndex(
            model_name='workconsent',
            index=models.Index(fields=['is_active'], name='tracking_wo_is_acti_050aa2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workconsent',
            unique_together={('freelancer', 'contract', 'device')},
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['freelancer', 'contract'], name='tracking_wo_freelan_3faa50_idx'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['device'], name='tracking_wo_device__398f40_idx'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['is_active'], name='tracking_wo_is_acti_b8be77_idx'),
        ),
        migrations.AddIndex(
            model_name='timeblock',
            index=models.Index(fields=['session'], name='tracking_ti_session_816952_idx'),
        ),
        migrations.AddIndex(
            model_name='timeblock',
            index=models.Index(fields=['session', 'started_at'], name='tracking_ti_session_306632_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeblock',
            unique_together={('session', 'block_index')},
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['freelancer'], name='tracking_ac_freelan_6eea88_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['session'], name='tracking_ac_session_17fb6a_idx'),
        ),
    ]
