# Generated by Django 5.2.7 on 2026-01-10 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workconsent',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='workconsent',
            name='user_agent',
        ),
    ]
