# Generated by Django 5.2.7 on 2026-01-10 16:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_contract_tracking_policy_contract_tracking_required'),
        ('tracking', '0002_remove_workconsent_ip_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workconsent',
            name='tracking_wo_device__234945_idx',
        ),
        migrations.AlterUniqueTogether(
            name='workconsent',
            unique_together={('freelancer', 'contract')},
        ),
        migrations.RemoveField(
            model_name='workconsent',
            name='device',
        ),
    ]
