# Generated by Django 5.2.7 on 2026-01-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_remove_workconsent_tracking_wo_device__234945_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
