# Generated by Django 5.2.7 on 2026-01-13 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_worksession_paused_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='device',
            name='tracking_de_freelan_fabfcb_idx',
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='tracking_de_device__c8aaa5_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeblock',
            name='tracking_ti_session_816952_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeblock',
            name='tracking_ti_session_306632_idx',
        ),
        migrations.RemoveIndex(
            model_name='worksession',
            name='tracking_wo_freelan_3faa50_idx',
        ),
        migrations.RemoveIndex(
            model_name='worksession',
            name='tracking_wo_device__398f40_idx',
        ),
        migrations.RemoveIndex(
            model_name='worksession',
            name='tracking_wo_is_acti_b8be77_idx',
        ),
        migrations.RemoveField(
            model_name='worksession',
            name='paused_at',
        ),
        migrations.AlterField(
            model_name='worksession',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracking.device'),
        ),
    ]
