# Generated by Django 5.2.7 on 2026-01-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_remove_device_tracking_de_freelan_fabfcb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
