# Generated by Django 5.2.7 on 2026-01-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_worksession_paused_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeblock',
            options={'ordering': ['started_at']},
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='tracking_ac_freelan_6eea88_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='tracking_ac_session_17fb6a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='timeblock',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='screenshot',
            name='screen_index',
        ),
        migrations.RemoveField(
            model_name='worksession',
            name='total_seconds',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('SESSION_START', 'Session Start'), ('SESSION_PAUSE', 'Session Pause'), ('SESSION_RESUME', 'Session Resume'), ('SESSION_STOP', 'Session Stop'), ('BLOCK_START', 'Block Start'), ('BLOCK_END', 'Block End'), ('SCREENSHOT', 'Screenshot'), ('IDLE', 'Idle'), ('ERROR', 'Error')], max_length=50),
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='timeblock',
            index=models.Index(fields=['session', 'started_at'], name='tracking_ti_session_306632_idx'),
        ),
        migrations.AddIndex(
            model_name='timeblock',
            index=models.Index(fields=['ended_at'], name='tracking_ti_ended_a_b71fe3_idx'),
        ),
        migrations.RemoveField(
            model_name='timeblock',
            name='block_index',
        ),
        migrations.RemoveField(
            model_name='timeblock',
            name='duration_seconds',
        ),
    ]
