# Generated by Django 5.2.7 on 2026-01-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_alter_timeblock_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshotwindow',
            name='offsets',
        ),
        migrations.RemoveField(
            model_name='screenshotwindow',
            name='seed',
        ),
        migrations.RemoveField(
            model_name='screenshotwindow',
            name='used_offsets',
        ),
        migrations.AddField(
            model_name='screenshotwindow',
            name='used_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='screenshotwindow',
            name='expected_count',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
