# Generated by Django 5.2.7 on 2026-01-15 03:58

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_remove_screenshotwindow_offsets_and_more'),
    ]

    operations = [
    migrations.AlterModelOptions(
        name='screenshotwindow',
        options={'ordering': ['window_start']},
    ),

    # 1️⃣ ADD FIELD FIRST
    migrations.AddField(
        model_name='screenshot',
        name='screenshot_window',
        field=models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='screenshots',
            to='tracking.screenshotwindow'
        ),
    ),

    # 2️⃣ NOW apply unique constraint
    migrations.AlterUniqueTogether(
        name='screenshot',
        unique_together={('screenshot_window', 'image_hash')},
    ),

    migrations.AddField(
        model_name='screenshotwindow',
        name='window_start',
        field=models.DateTimeField(default=django.utils.timezone.now),
        preserve_default=False,
    ),

    migrations.AddField(
        model_name='screenshotwindow',
        name='window_end',
        field=models.DateTimeField(),
        preserve_default=False,
    ),

    migrations.AlterField(
        model_name='screenshotwindow',
        name='time_block',
        field=models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='screenshot_windows',
            to='tracking.timeblock'
        ),
    ),

    migrations.AddIndex(
        model_name='screenshotwindow',
        index=models.Index(
            fields=['time_block', 'window_start'],
            name='tracking_sc_time_bl_eb489c_idx'
        ),
    ),

    migrations.AddIndex(
        model_name='screenshotwindow',
        index=models.Index(
            fields=['window_end'],
            name='tracking_sc_window__391efd_idx'
        ),
    ),

    migrations.RemoveField(
        model_name='screenshot',
        name='blur_reason',
    ),

    migrations.RemoveField(
        model_name='screenshot',
        name='is_blurred',
    ),
]

