# Generated by Django 5.2.7 on 2026-01-15 04:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_alter_screenshotwindow_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screenshotwindow',
            options={'ordering': ['start_at']},
        ),
        migrations.RemoveIndex(
            model_name='screenshotwindow',
            name='tracking_sc_time_bl_eb489c_idx',
        ),
        migrations.RemoveIndex(
            model_name='screenshotwindow',
            name='tracking_sc_window__391efd_idx',
        ),
        migrations.RenameField(
            model_name='screenshotwindow',
            old_name='window_end',
            new_name='end_at',
        ),
        migrations.RenameField(
            model_name='screenshotwindow',
            old_name='window_start',
            new_name='start_at',
        ),
        migrations.AlterUniqueTogether(
            name='screenshot',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='screenshot_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screenshots', to='tracking.screenshotwindow'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='taken_at_server',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='screenshotwindow',
            index=models.Index(fields=['time_block', 'start_at'], name='tracking_sc_time_bl_bb1802_idx'),
        ),
        migrations.AddIndex(
            model_name='screenshotwindow',
            index=models.Index(fields=['end_at'], name='tracking_sc_end_at_36604f_idx'),
        ),
        migrations.AddConstraint(
            model_name='screenshot',
            constraint=models.UniqueConstraint(fields=('screenshot_window', 'image_hash'), name='unique_screenshot_per_window'),
        ),
    ]
