# Generated by Django 5.2.7 on 2026-01-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_alter_screenshotwindow_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeblock',
            name='is_idle',
        ),
        migrations.AddField(
            model_name='timeblock',
            name='active_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='idle_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
