# Generated by Django 5.2.7 on 2026-01-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_remove_timeblock_is_idle_timeblock_active_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='flag_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='idle_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
