# Generated by Django 5.2.7 on 2026-01-17 06:14

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_alter_screenshot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblock',
            name='active_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='end_reason',
            field=models.CharField(
                max_length=10,
                choices=[
                    ('PAUSE', 'Paused by user'),
                    ('STOP', 'Session stopped'),
                    ('IDLE', 'Ended due to idle')
                ],
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='flag_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='idle_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        # Fix FK fields: remove invalid defaults
        migrations.AlterField(
            model_name='screenshot',
            name='window',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name='screenshots',
                to='tracking.screenshotwindow',
            ),
        ),
        migrations.AlterField(
            model_name='screenshotwindow',
            name='block',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name='windows',
                to='tracking.timeblock',
            ),
        ),
        # Remove invalid default for device_id
        migrations.AlterField(
            model_name='worksession',
            name='device_id',
            field=models.CharField(max_length=128),
        ),
    ]
