# Generated by Django 5.2.7 on 2026-01-24 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_timeblock_active_seconds_timeblock_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeblock',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('PAUSE', 'Paused by user'), ('STOP', 'Session stopped'), ('IDLE', 'Ended due to idle'), ('SYSTEM_SLEEP', 'System sleep')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='TimeBlockExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explanation', to='tracking.timeblock')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeblock_explanations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('block',), name='one_explanation_per_block')],
            },
        ),
    ]
