# Generated by Django 5.2.7 on 2026-01-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0015_alter_timeblock_end_reason_timeblockexplanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblock',
            name='flag_source',
            field=models.CharField(choices=[('NONE', 'Not flagged'), ('SYSTEM', 'System'), ('ADMIN', 'Admin')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
