# Generated by Django 5.2.7 on 2026-01-31 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0008_remove_pricing_fixed_price_remove_pricing_max_price_and_more'),
        ('tracking', '0016_timeblock_flag_source_timeblock_flagged_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.freelancerprofile'),
        ),
    ]
