# Generated by Django 5.2.7 on 2026-02-06 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_notificatio_recipie_4e3567_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('PROJECT_CREATED', 'Project Created'), ('PAYMENT_PROCESSED', 'Payment Processed'), ('ESCROW_FUNDED', 'Escrow Funded'), ('CONTRACT_COMPLETED', 'Contract Completed'), ('DISPUTE_OPENED', 'Dispute Opened')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activity_type', 'created_at'], name='notificatio_activit_47f290_idx')],
            },
        ),
    ]
