# Generated by Django 5.2.7 on 2026-02-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('PROJECT_CREATED', 'Project Created'), ('PAYMENT_PROCESSED', 'Payment Processed'), ('ESCROW_FUNDED', 'Escrow Funded'), ('ESCROW_RELEASED', 'Escrow Released'), ('ESCROW_REFUNDED', 'Escrow Refunded'), ('CONTRACT_COMPLETED', 'Contract Completed'), ('DISPUTE_OPENED', 'Dispute Opened')], max_length=50),
        ),
    ]
