# Generated by Django 5.2.7 on 2026-05-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_activitylog_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('PROJECT_CREATED', 'Project Created'), ('PROPOSAL_SUBMITTED', 'Proposal Submitted'), ('OFFER_SENT', 'Offer Sent'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('CONTRACT_CREATED', 'Contract Created'), ('PAYMENT_COMPLETED', 'Payment Completed'), (' PROFILE_UPDATED', 'Profile Updated'), ('SYSTEM', 'System Notification')], max_length=50),
        ),
    ]
